version: "3"
networks:
  default:
    external:
      name: gateway
  database:
    driver: bridge
    internal: true

services:
  index:
    build: .
    image: southclaws/openmp-index
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/prisma?schema=public
      LOG_LEVEL: debug
    ports:
      - 8080:80
    networks:
      - default
      - database
    depends_on:
      - postgres
    labels:
      traefik.enable: "true"
      traefik.docker.network: gateway
      traefik.http.routers.omp_index.rule: Host(`index.open.mp`)
      traefik.http.routers.omp_index.entrypoints: https
      traefik.http.routers.omp_index.tls.certresolver: default
      com.centurylinklabs.watchtower.enable: "true"

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${DATA_DIR}/openmp-index/postgres:/var/lib/postgresql/data
    networks:
      - database

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: u@e.com
      PGADMIN_DEFAULT_PASSWORD: default
    ports:
      - 8081:80
