version: "3"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: u@e.com
      PGADMIN_DEFAULT_PASSWORD: default
    ports:
      - 8081:80

  index:
    build: .
    image: southclaws/openmp-index
    environment:
      DATABASE_URL: postgresql://prisma:prisma@postgres:5432/prisma?schema=public
      LOG_LEVEL: debug
    ports:
      - 8080:80
